version: '3.8'

services:
  web:
    build:
      context: ./app
    command: gunicorn OnlineShop.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
    expose:
      - 8000
    env_file:
      - ./app/.env
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
    ports:
      - 1337:80
    depends_on:
      - web
  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data


volumes:
  postgres_data:
  static_volume:
  media_volume:
  redis_data: