# Generated by Django 5.0.1 on 2024-04-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_registration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
