# Generated by Django 5.0.1 on 2024-04-12 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_delete_purchasehistory_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('value', 'display'), ('value', 'display'), ('value', 'display'), ('value', 'display')], default='در حال پردازش', max_length=20),
        ),
    ]
