# Generated by Django 5.0.1 on 2024-04-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_purchasehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='09057939426', max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='recipient',
            field=models.CharField(default='مهدی علی محمدلو', max_length=50),
            preserve_default=False,
        ),
    ]
