# Generated by Django 5.0.1 on 2024-04-10 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
    ]
