# Generated by Django 5.0.1 on 2024-04-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_remove_order_delivery_status_order_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchaseHistory',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('value', 'display'), ('value', 'display'), ('value', 'display'), ('value', 'display')], default='pending', max_length=20),
        ),
    ]
